include:
  - board: seeeduino_xiao_ble
    shield: totem_left nice_oled
  - board: seeeduino_xiao_ble
    shield: totem_right nice_oled
  - board: seeeduino_xiao_ble
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
